* Encoding: UTF-8.
Regression
    /MISSING LISTWISE
    /STATISTICS COEFF OUTS R ANOVA
    /CRITERIA PIN(0.05) POUT(0.10)
    /NOORIGIN
    /DEPENDENT ID
    /METHOD ENTER Time Falls
    /RESIDUALS=OUTLIERS(MAHAL).
